# override permissions for any command
permissions:
  liveinteraction:
    whitelist: ${ [ ROLES.PILLAR_STAFF, ...getValuesRecursive(ROLES.ADMIN) ] }

  livecommand:
    whitelist: ${ [ ROLES.PILLAR_STAFF, ...getValuesRecursive(ROLES.ADMIN) ] }

activityStatus:
  message: To ALl Your Queries!

  # PLAYING = 0
  # STREAMING = 1
  # LISTENING = 2
  # WATCHING = 3
  # COMPETING = 5
  type: 2